/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WtfBookings {
    }
    interface WtfButton {
        "buttonLink": string;
        "iconUrl": string;
        "newTab": boolean;
        "textLeft": string;
        "textRight": string;
    }
    interface WtfHome {
    }
    interface WtfLogo {
    }
    interface WtfLonghorns {
    }
    interface WtfMedia {
    }
    interface WtfRoot {
    }
    interface WtfYoutube {
        "pause": () => Promise<void>;
        "play": () => Promise<void>;
        "videoId": string;
    }
}
declare global {
    interface HTMLWtfBookingsElement extends Components.WtfBookings, HTMLStencilElement {
    }
    var HTMLWtfBookingsElement: {
        prototype: HTMLWtfBookingsElement;
        new (): HTMLWtfBookingsElement;
    };
    interface HTMLWtfButtonElement extends Components.WtfButton, HTMLStencilElement {
    }
    var HTMLWtfButtonElement: {
        prototype: HTMLWtfButtonElement;
        new (): HTMLWtfButtonElement;
    };
    interface HTMLWtfHomeElement extends Components.WtfHome, HTMLStencilElement {
    }
    var HTMLWtfHomeElement: {
        prototype: HTMLWtfHomeElement;
        new (): HTMLWtfHomeElement;
    };
    interface HTMLWtfLogoElement extends Components.WtfLogo, HTMLStencilElement {
    }
    var HTMLWtfLogoElement: {
        prototype: HTMLWtfLogoElement;
        new (): HTMLWtfLogoElement;
    };
    interface HTMLWtfLonghornsElement extends Components.WtfLonghorns, HTMLStencilElement {
    }
    var HTMLWtfLonghornsElement: {
        prototype: HTMLWtfLonghornsElement;
        new (): HTMLWtfLonghornsElement;
    };
    interface HTMLWtfMediaElement extends Components.WtfMedia, HTMLStencilElement {
    }
    var HTMLWtfMediaElement: {
        prototype: HTMLWtfMediaElement;
        new (): HTMLWtfMediaElement;
    };
    interface HTMLWtfRootElement extends Components.WtfRoot, HTMLStencilElement {
    }
    var HTMLWtfRootElement: {
        prototype: HTMLWtfRootElement;
        new (): HTMLWtfRootElement;
    };
    interface HTMLWtfYoutubeElement extends Components.WtfYoutube, HTMLStencilElement {
    }
    var HTMLWtfYoutubeElement: {
        prototype: HTMLWtfYoutubeElement;
        new (): HTMLWtfYoutubeElement;
    };
    interface HTMLElementTagNameMap {
        "wtf-bookings": HTMLWtfBookingsElement;
        "wtf-button": HTMLWtfButtonElement;
        "wtf-home": HTMLWtfHomeElement;
        "wtf-logo": HTMLWtfLogoElement;
        "wtf-longhorns": HTMLWtfLonghornsElement;
        "wtf-media": HTMLWtfMediaElement;
        "wtf-root": HTMLWtfRootElement;
        "wtf-youtube": HTMLWtfYoutubeElement;
    }
}
declare namespace LocalJSX {
    interface WtfBookings {
    }
    interface WtfButton {
        "buttonLink"?: string;
        "iconUrl"?: string;
        "newTab"?: boolean;
        "textLeft"?: string;
        "textRight"?: string;
    }
    interface WtfHome {
    }
    interface WtfLogo {
    }
    interface WtfLonghorns {
    }
    interface WtfMedia {
    }
    interface WtfRoot {
    }
    interface WtfYoutube {
        "onPlayerReady"?: (event: CustomEvent<any>) => void;
        "onPlayerStart"?: (event: CustomEvent<any>) => void;
        "onPlayerStop"?: (event: CustomEvent<any>) => void;
        "videoId"?: string;
    }
    interface IntrinsicElements {
        "wtf-bookings": WtfBookings;
        "wtf-button": WtfButton;
        "wtf-home": WtfHome;
        "wtf-logo": WtfLogo;
        "wtf-longhorns": WtfLonghorns;
        "wtf-media": WtfMedia;
        "wtf-root": WtfRoot;
        "wtf-youtube": WtfYoutube;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wtf-bookings": LocalJSX.WtfBookings & JSXBase.HTMLAttributes<HTMLWtfBookingsElement>;
            "wtf-button": LocalJSX.WtfButton & JSXBase.HTMLAttributes<HTMLWtfButtonElement>;
            "wtf-home": LocalJSX.WtfHome & JSXBase.HTMLAttributes<HTMLWtfHomeElement>;
            "wtf-logo": LocalJSX.WtfLogo & JSXBase.HTMLAttributes<HTMLWtfLogoElement>;
            "wtf-longhorns": LocalJSX.WtfLonghorns & JSXBase.HTMLAttributes<HTMLWtfLonghornsElement>;
            "wtf-media": LocalJSX.WtfMedia & JSXBase.HTMLAttributes<HTMLWtfMediaElement>;
            "wtf-root": LocalJSX.WtfRoot & JSXBase.HTMLAttributes<HTMLWtfRootElement>;
            "wtf-youtube": LocalJSX.WtfYoutube & JSXBase.HTMLAttributes<HTMLWtfYoutubeElement>;
        }
    }
}
